version: '3.8'
services:
  api:
    image: ghcr.io/eesoymilk/health-statistic-api:main
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db # this is not localhost since we are connecting to a container named db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH0_ISSUER_URL: ${AUTH0_ISSUER_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}

  db:
    image: ghcr.io/eesoymilk/health-statistic-db:main
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - health-statistic-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  health-statistic-data:
