version: '3'
services:
  api:
    image: health-statistic-api:test
    ports:
      - "8080:8080"
    env_file: 
      - .env
      - .env.example # Fallback in case the program fails

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/db/health-statistic/data:/var/lib/postgresql/data
