version: '3.8'
services:
  api:
    # image: ghcr.io/eesoymilk/health-statistic-api:main
    image: ${API_IMAGE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db # this is not localhost since we are connecting to a container named db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      AUTH0_ISSUER_URL: ${AUTH0_ISSUER_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}

  db:
    # image: ghcr.io/eesoymilk/health-statistic-db:main
    image: ${DB_IMAGE}
    restart: always
    user: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - health-statistic-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  health-statistic-data:
