version: '3'
services:
  api:
    image: hsa:test
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: db # this is not localhost since we are connecting to a container named db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      AUTH0_ISSUER_URL: ${AUTH0_ISSUER_URL}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    # env_file: 
    #   - .env
    #   - .env.example # Fallback in case the program fails

  db:
    image: hsa-db:test
    restart: always
    # No need to expose ports since the container can talk to each other
    # ports:
    #   - "5444:5432"
    user: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - ~/db/health-statistic/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
