// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eesoymilk/health-statistic-api/ent/answer"
	"github.com/eesoymilk/health-statistic-api/ent/choice"
	"github.com/eesoymilk/health-statistic-api/ent/predicate"
	"github.com/eesoymilk/health-statistic-api/ent/question"
	"github.com/google/uuid"
)

// ChoiceUpdate is the builder for updating Choice entities.
type ChoiceUpdate struct {
	config
	hooks    []Hook
	mutation *ChoiceMutation
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (cu *ChoiceUpdate) Where(ps ...predicate.Choice) *ChoiceUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetBody sets the "body" field.
func (cu *ChoiceUpdate) SetBody(s string) *ChoiceUpdate {
	cu.mutation.SetBody(s)
	return cu
}

// SetOrder sets the "order" field.
func (cu *ChoiceUpdate) SetOrder(i int) *ChoiceUpdate {
	cu.mutation.ResetOrder()
	cu.mutation.SetOrder(i)
	return cu
}

// AddOrder adds i to the "order" field.
func (cu *ChoiceUpdate) AddOrder(i int) *ChoiceUpdate {
	cu.mutation.AddOrder(i)
	return cu
}

// SetQuesionID sets the "quesion" edge to the Question entity by ID.
func (cu *ChoiceUpdate) SetQuesionID(id uuid.UUID) *ChoiceUpdate {
	cu.mutation.SetQuesionID(id)
	return cu
}

// SetQuesion sets the "quesion" edge to the Question entity.
func (cu *ChoiceUpdate) SetQuesion(q *Question) *ChoiceUpdate {
	return cu.SetQuesionID(q.ID)
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (cu *ChoiceUpdate) SetAnswerID(id uuid.UUID) *ChoiceUpdate {
	cu.mutation.SetAnswerID(id)
	return cu
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (cu *ChoiceUpdate) SetNillableAnswerID(id *uuid.UUID) *ChoiceUpdate {
	if id != nil {
		cu = cu.SetAnswerID(*id)
	}
	return cu
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (cu *ChoiceUpdate) SetAnswer(a *Answer) *ChoiceUpdate {
	return cu.SetAnswerID(a.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (cu *ChoiceUpdate) Mutation() *ChoiceMutation {
	return cu.mutation
}

// ClearQuesion clears the "quesion" edge to the Question entity.
func (cu *ChoiceUpdate) ClearQuesion() *ChoiceUpdate {
	cu.mutation.ClearQuesion()
	return cu
}

// ClearAnswer clears the "answer" edge to the Answer entity.
func (cu *ChoiceUpdate) ClearAnswer() *ChoiceUpdate {
	cu.mutation.ClearAnswer()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChoiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChoiceUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChoiceUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChoiceUpdate) check() error {
	if v, ok := cu.mutation.Body(); ok {
		if err := choice.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Choice.body": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Order(); ok {
		if err := choice.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "Choice.order": %w`, err)}
		}
	}
	if _, ok := cu.mutation.QuesionID(); cu.mutation.QuesionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Choice.quesion"`)
	}
	return nil
}

func (cu *ChoiceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Body(); ok {
		_spec.SetField(choice.FieldBody, field.TypeString, value)
	}
	if value, ok := cu.mutation.Order(); ok {
		_spec.SetField(choice.FieldOrder, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedOrder(); ok {
		_spec.AddField(choice.FieldOrder, field.TypeInt, value)
	}
	if cu.mutation.QuesionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuesionTable,
			Columns: []string{choice.QuesionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.QuesionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuesionTable,
			Columns: []string{choice.QuesionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.AnswerTable,
			Columns: []string{choice.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.AnswerTable,
			Columns: []string{choice.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChoiceUpdateOne is the builder for updating a single Choice entity.
type ChoiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChoiceMutation
}

// SetBody sets the "body" field.
func (cuo *ChoiceUpdateOne) SetBody(s string) *ChoiceUpdateOne {
	cuo.mutation.SetBody(s)
	return cuo
}

// SetOrder sets the "order" field.
func (cuo *ChoiceUpdateOne) SetOrder(i int) *ChoiceUpdateOne {
	cuo.mutation.ResetOrder()
	cuo.mutation.SetOrder(i)
	return cuo
}

// AddOrder adds i to the "order" field.
func (cuo *ChoiceUpdateOne) AddOrder(i int) *ChoiceUpdateOne {
	cuo.mutation.AddOrder(i)
	return cuo
}

// SetQuesionID sets the "quesion" edge to the Question entity by ID.
func (cuo *ChoiceUpdateOne) SetQuesionID(id uuid.UUID) *ChoiceUpdateOne {
	cuo.mutation.SetQuesionID(id)
	return cuo
}

// SetQuesion sets the "quesion" edge to the Question entity.
func (cuo *ChoiceUpdateOne) SetQuesion(q *Question) *ChoiceUpdateOne {
	return cuo.SetQuesionID(q.ID)
}

// SetAnswerID sets the "answer" edge to the Answer entity by ID.
func (cuo *ChoiceUpdateOne) SetAnswerID(id uuid.UUID) *ChoiceUpdateOne {
	cuo.mutation.SetAnswerID(id)
	return cuo
}

// SetNillableAnswerID sets the "answer" edge to the Answer entity by ID if the given value is not nil.
func (cuo *ChoiceUpdateOne) SetNillableAnswerID(id *uuid.UUID) *ChoiceUpdateOne {
	if id != nil {
		cuo = cuo.SetAnswerID(*id)
	}
	return cuo
}

// SetAnswer sets the "answer" edge to the Answer entity.
func (cuo *ChoiceUpdateOne) SetAnswer(a *Answer) *ChoiceUpdateOne {
	return cuo.SetAnswerID(a.ID)
}

// Mutation returns the ChoiceMutation object of the builder.
func (cuo *ChoiceUpdateOne) Mutation() *ChoiceMutation {
	return cuo.mutation
}

// ClearQuesion clears the "quesion" edge to the Question entity.
func (cuo *ChoiceUpdateOne) ClearQuesion() *ChoiceUpdateOne {
	cuo.mutation.ClearQuesion()
	return cuo
}

// ClearAnswer clears the "answer" edge to the Answer entity.
func (cuo *ChoiceUpdateOne) ClearAnswer() *ChoiceUpdateOne {
	cuo.mutation.ClearAnswer()
	return cuo
}

// Where appends a list predicates to the ChoiceUpdate builder.
func (cuo *ChoiceUpdateOne) Where(ps ...predicate.Choice) *ChoiceUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChoiceUpdateOne) Select(field string, fields ...string) *ChoiceUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Choice entity.
func (cuo *ChoiceUpdateOne) Save(ctx context.Context) (*Choice, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChoiceUpdateOne) SaveX(ctx context.Context) *Choice {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChoiceUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChoiceUpdateOne) check() error {
	if v, ok := cuo.mutation.Body(); ok {
		if err := choice.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "Choice.body": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Order(); ok {
		if err := choice.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "Choice.order": %w`, err)}
		}
	}
	if _, ok := cuo.mutation.QuesionID(); cuo.mutation.QuesionCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Choice.quesion"`)
	}
	return nil
}

func (cuo *ChoiceUpdateOne) sqlSave(ctx context.Context) (_node *Choice, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(choice.Table, choice.Columns, sqlgraph.NewFieldSpec(choice.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Choice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, choice.FieldID)
		for _, f := range fields {
			if !choice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != choice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Body(); ok {
		_spec.SetField(choice.FieldBody, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Order(); ok {
		_spec.SetField(choice.FieldOrder, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedOrder(); ok {
		_spec.AddField(choice.FieldOrder, field.TypeInt, value)
	}
	if cuo.mutation.QuesionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuesionTable,
			Columns: []string{choice.QuesionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.QuesionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.QuesionTable,
			Columns: []string{choice.QuesionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.AnswerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.AnswerTable,
			Columns: []string{choice.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AnswerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   choice.AnswerTable,
			Columns: []string{choice.AnswerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Choice{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{choice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
