// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eesoymilk/health-statistic-api/ent/healthkit"
	"github.com/eesoymilk/health-statistic-api/ent/predicate"
	"github.com/eesoymilk/health-statistic-api/ent/user"
)

// HealthKitUpdate is the builder for updating HealthKit entities.
type HealthKitUpdate struct {
	config
	hooks    []Hook
	mutation *HealthKitMutation
}

// Where appends a list predicates to the HealthKitUpdate builder.
func (hku *HealthKitUpdate) Where(ps ...predicate.HealthKit) *HealthKitUpdate {
	hku.mutation.Where(ps...)
	return hku
}

// SetStartDate sets the "start_date" field.
func (hku *HealthKitUpdate) SetStartDate(t time.Time) *HealthKitUpdate {
	hku.mutation.SetStartDate(t)
	return hku
}

// SetEndDate sets the "end_date" field.
func (hku *HealthKitUpdate) SetEndDate(t time.Time) *HealthKitUpdate {
	hku.mutation.SetEndDate(t)
	return hku
}

// SetStepCount sets the "step_count" field.
func (hku *HealthKitUpdate) SetStepCount(f float64) *HealthKitUpdate {
	hku.mutation.ResetStepCount()
	hku.mutation.SetStepCount(f)
	return hku
}

// AddStepCount adds f to the "step_count" field.
func (hku *HealthKitUpdate) AddStepCount(f float64) *HealthKitUpdate {
	hku.mutation.AddStepCount(f)
	return hku
}

// SetUserID sets the "user" edge to the User entity by ID.
func (hku *HealthKitUpdate) SetUserID(id string) *HealthKitUpdate {
	hku.mutation.SetUserID(id)
	return hku
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (hku *HealthKitUpdate) SetNillableUserID(id *string) *HealthKitUpdate {
	if id != nil {
		hku = hku.SetUserID(*id)
	}
	return hku
}

// SetUser sets the "user" edge to the User entity.
func (hku *HealthKitUpdate) SetUser(u *User) *HealthKitUpdate {
	return hku.SetUserID(u.ID)
}

// Mutation returns the HealthKitMutation object of the builder.
func (hku *HealthKitUpdate) Mutation() *HealthKitMutation {
	return hku.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (hku *HealthKitUpdate) ClearUser() *HealthKitUpdate {
	hku.mutation.ClearUser()
	return hku
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hku *HealthKitUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hku.sqlSave, hku.mutation, hku.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hku *HealthKitUpdate) SaveX(ctx context.Context) int {
	affected, err := hku.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hku *HealthKitUpdate) Exec(ctx context.Context) error {
	_, err := hku.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hku *HealthKitUpdate) ExecX(ctx context.Context) {
	if err := hku.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hku *HealthKitUpdate) check() error {
	if v, ok := hku.mutation.StepCount(); ok {
		if err := healthkit.StepCountValidator(v); err != nil {
			return &ValidationError{Name: "step_count", err: fmt.Errorf(`ent: validator failed for field "HealthKit.step_count": %w`, err)}
		}
	}
	return nil
}

func (hku *HealthKitUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := hku.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthkit.Table, healthkit.Columns, sqlgraph.NewFieldSpec(healthkit.FieldID, field.TypeUUID))
	if ps := hku.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hku.mutation.StartDate(); ok {
		_spec.SetField(healthkit.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := hku.mutation.EndDate(); ok {
		_spec.SetField(healthkit.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := hku.mutation.StepCount(); ok {
		_spec.SetField(healthkit.FieldStepCount, field.TypeFloat64, value)
	}
	if value, ok := hku.mutation.AddedStepCount(); ok {
		_spec.AddField(healthkit.FieldStepCount, field.TypeFloat64, value)
	}
	if hku.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthkit.UserTable,
			Columns: []string{healthkit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hku.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthkit.UserTable,
			Columns: []string{healthkit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hku.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthkit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hku.mutation.done = true
	return n, nil
}

// HealthKitUpdateOne is the builder for updating a single HealthKit entity.
type HealthKitUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HealthKitMutation
}

// SetStartDate sets the "start_date" field.
func (hkuo *HealthKitUpdateOne) SetStartDate(t time.Time) *HealthKitUpdateOne {
	hkuo.mutation.SetStartDate(t)
	return hkuo
}

// SetEndDate sets the "end_date" field.
func (hkuo *HealthKitUpdateOne) SetEndDate(t time.Time) *HealthKitUpdateOne {
	hkuo.mutation.SetEndDate(t)
	return hkuo
}

// SetStepCount sets the "step_count" field.
func (hkuo *HealthKitUpdateOne) SetStepCount(f float64) *HealthKitUpdateOne {
	hkuo.mutation.ResetStepCount()
	hkuo.mutation.SetStepCount(f)
	return hkuo
}

// AddStepCount adds f to the "step_count" field.
func (hkuo *HealthKitUpdateOne) AddStepCount(f float64) *HealthKitUpdateOne {
	hkuo.mutation.AddStepCount(f)
	return hkuo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (hkuo *HealthKitUpdateOne) SetUserID(id string) *HealthKitUpdateOne {
	hkuo.mutation.SetUserID(id)
	return hkuo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (hkuo *HealthKitUpdateOne) SetNillableUserID(id *string) *HealthKitUpdateOne {
	if id != nil {
		hkuo = hkuo.SetUserID(*id)
	}
	return hkuo
}

// SetUser sets the "user" edge to the User entity.
func (hkuo *HealthKitUpdateOne) SetUser(u *User) *HealthKitUpdateOne {
	return hkuo.SetUserID(u.ID)
}

// Mutation returns the HealthKitMutation object of the builder.
func (hkuo *HealthKitUpdateOne) Mutation() *HealthKitMutation {
	return hkuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (hkuo *HealthKitUpdateOne) ClearUser() *HealthKitUpdateOne {
	hkuo.mutation.ClearUser()
	return hkuo
}

// Where appends a list predicates to the HealthKitUpdate builder.
func (hkuo *HealthKitUpdateOne) Where(ps ...predicate.HealthKit) *HealthKitUpdateOne {
	hkuo.mutation.Where(ps...)
	return hkuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (hkuo *HealthKitUpdateOne) Select(field string, fields ...string) *HealthKitUpdateOne {
	hkuo.fields = append([]string{field}, fields...)
	return hkuo
}

// Save executes the query and returns the updated HealthKit entity.
func (hkuo *HealthKitUpdateOne) Save(ctx context.Context) (*HealthKit, error) {
	return withHooks(ctx, hkuo.sqlSave, hkuo.mutation, hkuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hkuo *HealthKitUpdateOne) SaveX(ctx context.Context) *HealthKit {
	node, err := hkuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (hkuo *HealthKitUpdateOne) Exec(ctx context.Context) error {
	_, err := hkuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hkuo *HealthKitUpdateOne) ExecX(ctx context.Context) {
	if err := hkuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hkuo *HealthKitUpdateOne) check() error {
	if v, ok := hkuo.mutation.StepCount(); ok {
		if err := healthkit.StepCountValidator(v); err != nil {
			return &ValidationError{Name: "step_count", err: fmt.Errorf(`ent: validator failed for field "HealthKit.step_count": %w`, err)}
		}
	}
	return nil
}

func (hkuo *HealthKitUpdateOne) sqlSave(ctx context.Context) (_node *HealthKit, err error) {
	if err := hkuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(healthkit.Table, healthkit.Columns, sqlgraph.NewFieldSpec(healthkit.FieldID, field.TypeUUID))
	id, ok := hkuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HealthKit.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := hkuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, healthkit.FieldID)
		for _, f := range fields {
			if !healthkit.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != healthkit.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := hkuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hkuo.mutation.StartDate(); ok {
		_spec.SetField(healthkit.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := hkuo.mutation.EndDate(); ok {
		_spec.SetField(healthkit.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := hkuo.mutation.StepCount(); ok {
		_spec.SetField(healthkit.FieldStepCount, field.TypeFloat64, value)
	}
	if value, ok := hkuo.mutation.AddedStepCount(); ok {
		_spec.AddField(healthkit.FieldStepCount, field.TypeFloat64, value)
	}
	if hkuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthkit.UserTable,
			Columns: []string{healthkit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := hkuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   healthkit.UserTable,
			Columns: []string{healthkit.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &HealthKit{config: hkuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, hkuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{healthkit.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	hkuo.mutation.done = true
	return _node, nil
}
