// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/eesoymilk/health-statistic-api/ent/answer"
	"github.com/eesoymilk/health-statistic-api/ent/questionnaire"
	"github.com/eesoymilk/health-statistic-api/ent/questionnaireresponse"
	"github.com/eesoymilk/health-statistic-api/ent/user"
	"github.com/google/uuid"
)

// QuestionnaireResponseCreate is the builder for creating a QuestionnaireResponse entity.
type QuestionnaireResponseCreate struct {
	config
	mutation *QuestionnaireResponseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (qrc *QuestionnaireResponseCreate) SetCreatedAt(t time.Time) *QuestionnaireResponseCreate {
	qrc.mutation.SetCreatedAt(t)
	return qrc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (qrc *QuestionnaireResponseCreate) SetNillableCreatedAt(t *time.Time) *QuestionnaireResponseCreate {
	if t != nil {
		qrc.SetCreatedAt(*t)
	}
	return qrc
}

// SetID sets the "id" field.
func (qrc *QuestionnaireResponseCreate) SetID(u uuid.UUID) *QuestionnaireResponseCreate {
	qrc.mutation.SetID(u)
	return qrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (qrc *QuestionnaireResponseCreate) SetNillableID(u *uuid.UUID) *QuestionnaireResponseCreate {
	if u != nil {
		qrc.SetID(*u)
	}
	return qrc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (qrc *QuestionnaireResponseCreate) SetUserID(id string) *QuestionnaireResponseCreate {
	qrc.mutation.SetUserID(id)
	return qrc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (qrc *QuestionnaireResponseCreate) SetNillableUserID(id *string) *QuestionnaireResponseCreate {
	if id != nil {
		qrc = qrc.SetUserID(*id)
	}
	return qrc
}

// SetUser sets the "user" edge to the User entity.
func (qrc *QuestionnaireResponseCreate) SetUser(u *User) *QuestionnaireResponseCreate {
	return qrc.SetUserID(u.ID)
}

// SetQuestionnaireID sets the "questionnaire" edge to the Questionnaire entity by ID.
func (qrc *QuestionnaireResponseCreate) SetQuestionnaireID(id uuid.UUID) *QuestionnaireResponseCreate {
	qrc.mutation.SetQuestionnaireID(id)
	return qrc
}

// SetNillableQuestionnaireID sets the "questionnaire" edge to the Questionnaire entity by ID if the given value is not nil.
func (qrc *QuestionnaireResponseCreate) SetNillableQuestionnaireID(id *uuid.UUID) *QuestionnaireResponseCreate {
	if id != nil {
		qrc = qrc.SetQuestionnaireID(*id)
	}
	return qrc
}

// SetQuestionnaire sets the "questionnaire" edge to the Questionnaire entity.
func (qrc *QuestionnaireResponseCreate) SetQuestionnaire(q *Questionnaire) *QuestionnaireResponseCreate {
	return qrc.SetQuestionnaireID(q.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (qrc *QuestionnaireResponseCreate) AddAnswerIDs(ids ...uuid.UUID) *QuestionnaireResponseCreate {
	qrc.mutation.AddAnswerIDs(ids...)
	return qrc
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (qrc *QuestionnaireResponseCreate) AddAnswers(a ...*Answer) *QuestionnaireResponseCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return qrc.AddAnswerIDs(ids...)
}

// Mutation returns the QuestionnaireResponseMutation object of the builder.
func (qrc *QuestionnaireResponseCreate) Mutation() *QuestionnaireResponseMutation {
	return qrc.mutation
}

// Save creates the QuestionnaireResponse in the database.
func (qrc *QuestionnaireResponseCreate) Save(ctx context.Context) (*QuestionnaireResponse, error) {
	qrc.defaults()
	return withHooks(ctx, qrc.sqlSave, qrc.mutation, qrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (qrc *QuestionnaireResponseCreate) SaveX(ctx context.Context) *QuestionnaireResponse {
	v, err := qrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qrc *QuestionnaireResponseCreate) Exec(ctx context.Context) error {
	_, err := qrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qrc *QuestionnaireResponseCreate) ExecX(ctx context.Context) {
	if err := qrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (qrc *QuestionnaireResponseCreate) defaults() {
	if _, ok := qrc.mutation.CreatedAt(); !ok {
		v := questionnaireresponse.DefaultCreatedAt()
		qrc.mutation.SetCreatedAt(v)
	}
	if _, ok := qrc.mutation.ID(); !ok {
		v := questionnaireresponse.DefaultID()
		qrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (qrc *QuestionnaireResponseCreate) check() error {
	if _, ok := qrc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QuestionnaireResponse.created_at"`)}
	}
	return nil
}

func (qrc *QuestionnaireResponseCreate) sqlSave(ctx context.Context) (*QuestionnaireResponse, error) {
	if err := qrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := qrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, qrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	qrc.mutation.id = &_node.ID
	qrc.mutation.done = true
	return _node, nil
}

func (qrc *QuestionnaireResponseCreate) createSpec() (*QuestionnaireResponse, *sqlgraph.CreateSpec) {
	var (
		_node = &QuestionnaireResponse{config: qrc.config}
		_spec = sqlgraph.NewCreateSpec(questionnaireresponse.Table, sqlgraph.NewFieldSpec(questionnaireresponse.FieldID, field.TypeUUID))
	)
	if id, ok := qrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := qrc.mutation.CreatedAt(); ok {
		_spec.SetField(questionnaireresponse.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := qrc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionnaireresponse.UserTable,
			Columns: []string{questionnaireresponse.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_questionnaire_responses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qrc.mutation.QuestionnaireIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionnaireresponse.QuestionnaireTable,
			Columns: []string{questionnaireresponse.QuestionnaireColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.questionnaire_questionnaire_responses = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := qrc.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questionnaireresponse.AnswersTable,
			Columns: []string{questionnaireresponse.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionnaireResponseCreateBulk is the builder for creating many QuestionnaireResponse entities in bulk.
type QuestionnaireResponseCreateBulk struct {
	config
	builders []*QuestionnaireResponseCreate
}

// Save creates the QuestionnaireResponse entities in the database.
func (qrcb *QuestionnaireResponseCreateBulk) Save(ctx context.Context) ([]*QuestionnaireResponse, error) {
	specs := make([]*sqlgraph.CreateSpec, len(qrcb.builders))
	nodes := make([]*QuestionnaireResponse, len(qrcb.builders))
	mutators := make([]Mutator, len(qrcb.builders))
	for i := range qrcb.builders {
		func(i int, root context.Context) {
			builder := qrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionnaireResponseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, qrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, qrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, qrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (qrcb *QuestionnaireResponseCreateBulk) SaveX(ctx context.Context) []*QuestionnaireResponse {
	v, err := qrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (qrcb *QuestionnaireResponseCreateBulk) Exec(ctx context.Context) error {
	_, err := qrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (qrcb *QuestionnaireResponseCreateBulk) ExecX(ctx context.Context) {
	if err := qrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
