// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/eesoymilk/health-statistic-api/ent/schema"
	"github.com/eesoymilk/health-statistic-api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescBirthYear is the schema descriptor for birth_year field.
	userDescBirthYear := userFields[0].Descriptor()
	// user.BirthYearValidator is a validator for the "birth_year" field. It is called by the builders before save.
	user.BirthYearValidator = userDescBirthYear.Validators[0].(func(int) error)
	// userDescHeight is the schema descriptor for height field.
	userDescHeight := userFields[1].Descriptor()
	// user.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	user.HeightValidator = userDescHeight.Validators[0].(func(float64) error)
	// userDescWeight is the schema descriptor for weight field.
	userDescWeight := userFields[2].Descriptor()
	// user.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	user.WeightValidator = userDescWeight.Validators[0].(func(float64) error)
	// userDescMedicalHistory is the schema descriptor for medical_history field.
	userDescMedicalHistory := userFields[7].Descriptor()
	// user.MedicalHistoryValidator is a validator for the "medical_history" field. It is called by the builders before save.
	user.MedicalHistoryValidator = userDescMedicalHistory.Validators[0].(func(string) error)
	// userDescMedicationStatus is the schema descriptor for medication_status field.
	userDescMedicationStatus := userFields[8].Descriptor()
	// user.MedicationStatusValidator is a validator for the "medication_status" field. It is called by the builders before save.
	user.MedicationStatusValidator = userDescMedicationStatus.Validators[0].(func(string) error)
}
