name: Update gh-pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gh_pages.yml"
      - "docs/swagger.json"

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Push to gh-pages
        run: |
          git checkout gh-pages
          git checkout main docs/swagger.json
          rm -f swagger.json
          mv docs/swagger.json .
          rm -rf docs
          git add swagger.json
          git commit -m 'Update swagger documentation'
          git push origin gh-pages
