// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Answer is the predicate function for answer builders.
type Answer func(*sql.Selector)

// Choice is the predicate function for choice builders.
type Choice func(*sql.Selector)

// HealthKit is the predicate function for healthkit builders.
type HealthKit func(*sql.Selector)

// MyCard is the predicate function for mycard builders.
type MyCard func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// Price is the predicate function for price builders.
type Price func(*sql.Selector)

// Question is the predicate function for question builders.
type Question func(*sql.Selector)

// Questionnaire is the predicate function for questionnaire builders.
type Questionnaire func(*sql.Selector)

// QuestionnaireResponse is the predicate function for questionnaireresponse builders.
type QuestionnaireResponse func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
